translator = {
    "Polowanie na Czerwony Październik": "The Hunt for Red October",
    "Rick & Morty": "Rick & Morty",
    "Teoria wielkiego podrywu": "The Big Bang Theory",
    "Waleczne serce": "Braveheart",
    "The Expanse": "The Expanse",
    "Miasteczko South Park": "South Park",
    "Kraina Lodu": "Frozen",
    "Dziennik Bridget Jones": "Bridget Jones's Diary",
    "Kapitan Ameryka: Wojna bohaterów": "Captain America: Civil War",
    "Avengers: Czas Ultrona": "Avengers: Age of Ultron",
    "Terminator 2": "Terminator 2: Judgment Day",
    "Planeta Singli": "Planet Single",
    "List do M.": "Letters to Santa",
    "List do M. 2": "Letters to Santa 2",
    "Forrest Gump": "Forrest Gump",
    "Ex Machina": "Ex Machina",
    "Gran Torino": "Gran Torino",
    "Cicha Noc": "Silent Night",
    "Battleship: Bitwa o Ziemię": "Battleship",
    "Narodziny Gwiazdy": "A Star Is Born",
    "Kapitan Phillips": "Captain Phillips",
    "Grand Budapest Hotel": "Grand Budapest Hotel",
    "Wyjazd integracyjny": "Integration Trip",
    "John Wick": "John Wick",
    "John Wick 2": "John Wick: Chapter 2",
    "John Wick 3": "John Wick: Chapter 3 - Parabellum",
    "Narcos": "Narcos",
    "Terminal": "The Terminal",
    "Ona": "Her",
    "Whiplash": "Whiplash",
    "Diabeł ubiera się u Prady": "The Devil Wears Prada",
    "Dom z papieru": "La Casa De Papel",
    "Snowpiercer": "Snowpiercer",
    "Szpital New Amsterdam": "New Amsterdam",
    "Diuna": "Dune",
    "Jak poznałem waszą matkę": "How I met your mother",
    "Chłopaki z baraków": "Trailer Park Boys",
    "Sherlock": "Sherlock",
    "Ty": "You",
    "Gotham": "Gotham",
    "One Direction: All For One": "One Direction: All For One",
    "Love Death + Robots": "Love, Death & Robots",
    "Wiedźmin": "The Witcher",
    "Babydriver": "Baby driver",
    "Siedem": "Seven",
    "Jak zostalem gangsterem. Historia prawdziwa": "How I became a gangster - true story",
    "The Office": "The Office",
    "Dark": "Dark",
    "Stranger Things": "Stranger Things",
    "The Umbrella Academy": "The Umbrella Academy",
    "House of Cards": "La Casa De Papel",
    "Wiedźmin: Zmora Wilka": "The Witcher: Nightmare of the Wolf",
    "Kod wart miliardy dolarów": "The Billion Dollar Code",
    "Nie czas umierać": "No Time To Die",
    "Lupin": "Lupin",
    "Incepcja": "Inception",
    "W garniturach": "The Suits",
    "Sex education": "Sex education",
    "Doktor House": "House",
    "DOTA: Dragon's Blood": "DOTA: Dragon's Blood",
    "Lucyfer": "Lucifer",
    "Venom: Let There Be Carnage": "Venom 2: Carnage",
    "Gladiator": "Gladiator",
    "Obecność 3: Na rozkaz diabła": "The Conjuring: The Devil Made Me Do It",
    "Czarna Wdowa": "Black Widow",
    "Norbit": "Norbit",
    "The Walking Dead": "The Walking Dead",
    "Veer-Zaara": "Veer-Zaara",
    "Hardcore Henry": "Hardcore Henry",
    "Nawiedzony dwór w Bly": "The Haunting of Bly Manor",
    "Chris Chan: A Comprehensive History": "Chris Chan: A Comprehensive History",
    "This Is Monsters": "This Is Monsters",
    "Kung Fury": "Kung Fury",
    "Planeta skarbów": "Treasure Planet",
    "Squid Game": "Squid Game",
    "Atypowy": "Atypical",
    "Saga 'Zmierzch'": "The Twilight Saga",
    "Joker": "Joker",
    "Mroczny Rycerz powstaje": "The Dark Knight Rises",
    "Kevin sam w domu": "Home Alone",
    "Harry Potter i więzień Azkabanu": "Harry Potter and the Prisoner of Azkaban",
    "Split": "Split",
    "Super zioło": "How high",
    "Różowe lata 70.": "That '70s Show",
    "Zombiebobry": "Zombeavers",
    "Supersamiec": "Superbad",
    "Jestem Bogiem": "Limitless",
    "Rozczarowani": "Disenchantment",
    "Przyjaciele": "Friends",
    "Igrzyska śmierci": "The Hunger Games",
    "Constantine": "Constantine",
}